services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env.docker

    ports:
      - "8000:8000"

    # Development
    command: python manage.py runserver 0.0.0.0:8000

    restart: unless-stopped
